version: '3.8'

services:
  database:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - 3308:3306
    networks:
      - net-todoapp
    volumes:
      - todo-mysql-vol:/var/lib/mysql
networks:
  net-todoapp:
    driver: bridge
volumes:
  todo-mysql-vol:
